
package com.cxfwb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.cxfwb.ObjectFactory;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version:
 * 2.0
 * 
 */
@WebService(name = "IcxfWB", targetNamespace = "http://cxfWB.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IcxfWB
{

	/**
	 * 
	 * @param data杀杀杀3
	 * @param vssid
	 * @param token
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "csg_message")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "csg_message", targetNamespace = "http://cxfWB.com/", className = "com.cxfwb.CsgMessage")
	@ResponseWrapper(localName = "csg_messageResponse", targetNamespace = "http://cxfWB.com/", className = "com.cxfwb.CsgMessageResponse")
	public String csgMessage(@WebParam(name = "vssid", targetNamespace = "") String vssid,
			@WebParam(name = "token", targetNamespace = "") String token,
			@WebParam(name = "data", targetNamespace = "") String data);

}
