
package com.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceDelegate", targetNamespace = "http://service.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceDelegate {


    /**
     * 
     * @param data
     * @param token
     * @return
     * returns java.lang.String
     */
    @WebMethod(operationName = "csg_message")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "csg_message", targetNamespace = "http://service.com/", className = "com.service.CsgMessage")
    @ResponseWrapper(localName = "csg_messageResponse", targetNamespace = "http://service.com/", className = "com.service.CsgMessageResponse")
    public String csgMessage(
    	@WebParam(name = "vssid", targetNamespace = "")
        String vssid,
        @WebParam(name = "data", targetNamespace = "")
        String data,
        @WebParam(name = "token", targetNamespace = "")
        String token);

}
